name: pipeline

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_RAW_BUCKET: airflow-ug-raw
      R2_PROCESSED_BUCKET: airflow-ug-processed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: make setup
      - run: make run
